# Generated by Django 5.2.9 on 2025-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterskill',
            name='skill_name',
            field=models.TextField(unique=True),
        ),
    ]
