# Generated by Django 5.2.7 on 2025-11-13 04:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2dff547e-a53d-48ae-abdd-053956b69f3a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5952469f-aa3a-44d1-b065-0144ba984bbf'), primary_key=True, serialize=False),
        ),
    ]
