# Generated by Django 5.2.7 on 2025-11-13 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ed27651-7af6-4136-b37e-00fe6b846811'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef5c816b-3e9f-4c7e-9b38-92cb4df2ba90'), primary_key=True, serialize=False),
        ),
    ]
