# Generated by Django 5.2.9 on 2025-12-30 08:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
