# Generated by Django 5.2.7 on 2025-11-13 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'industries',
            },
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='career.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_recommendations',
            },
        ),
        migrations.CreateModel(
            name='CareerSpecialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='career.career')),
            ],
            options={
                'db_table': 'career_specializations',
            },
        ),
        migrations.AddField(
            model_name='career',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to='career.industry'),
        ),
        migrations.CreateModel(
            name='CareerRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='career.career')),
            ],
            options={
                'verbose_name': 'Career Required Skill',
                'verbose_name_plural': 'Career Required Skills',
                'db_table': 'career_required_skills',
                'unique_together': {('career', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='CareerTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='career.career')),
            ],
            options={
                'verbose_name': 'Career Trait',
                'verbose_name_plural': 'Career Traits',
                'db_table': 'career_traits',
                'unique_together': {('career', 'trait_name')},
            },
        ),
    ]
