# Generated by Django 5.2.9 on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0002_test_keyword_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="industry",
            name="mbti_map",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="industry",
            name="holland_map",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
