# Generated by Django 5.2.8 on 2026-01-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_industry_score_maps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={},
        ),
        migrations.RemoveField(
            model_name='industry',
            name='holland_codes',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='mbti_codes',
        ),
        migrations.AlterField(
            model_name='industry',
            name='holland_map',
            field=models.JSONField(blank=True, default=dict, help_text='Map Holland -> score. Ví dụ: {"R": 40, "I": 90}'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='mbti_map',
            field=models.JSONField(blank=True, default=dict, help_text='Map MBTI -> score. Ví dụ: {"INTJ": 90, "ENTP": 70}'),
        ),
    ]
