# Generated by Django 5.2.7 on 2025-11-13 04:21

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        ('courses', '0001_initial'),
        ('users', '0002_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEmbedding',
            fields=[
                ('career', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='career.career')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'career_embeddings',
            },
        ),
        migrations.CreateModel(
            name='CourseEmbedding',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='courses.course')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'course_embeddings',
            },
        ),
        migrations.CreateModel(
            name='SpecializationEmbedding',
            fields=[
                ('specialization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='career.careerspecialization')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'specialization_embeddings',
            },
        ),
        migrations.CreateModel(
            name='UserEmbedding',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_embeddings',
            },
        ),
    ]
