# Generated by Django 5.2.9 on 2025-12-06 08:04

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
