# Generated by Django 5.2.9 on 2026-01-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cấu hình mặc định', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Chỉ có 1 cấu hình được kích hoạt tại 1 thời điểm')),
                ('temperature', models.FloatField(default=0.7, help_text='Độ sáng tạo (0.0 - 1.0)')),
                ('role_description', models.TextField(default='Bạn là AI Career Advisor chuyên nghiệp...', help_text='Mô tả vai trò cốt lõi của AI.')),
                ('missing_profile_template', models.TextField(help_text='Prompt dùng khi user chưa cập nhật hồ sơ. Dùng biến {user_profile_context}, {chat_history_text}, {prompt}')),
                ('standard_prompt_template', models.TextField(help_text='Prompt chuẩn. Dùng các biến: {user_profile_context}, {rag_context}, {chat_history_text}, {prompt}, {current_job}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='context_used',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
