# Generated by Django 5.2.9 on 2026-01-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aipromptconfig_chatmessage_context_used'),
        ('ai', '0002_chatmessage_context_used'),
    ]

    operations = [
    ]
